/** @type {import('next').NextConfig} */
const nextConfig = {
  /**
   * Keeps both deployment targets alive: GitHub Pages (the live host for
   * bjbeyond.it) serves `out/` as-is, and Vercel serves the same output with no
   * extra configuration. It also copies the standalone apps in `public/`
   * (/phoenix, /frequency) and the legacy /pages/*.html verbatim, so every
   * pre-existing URL keeps resolving.
   */
  output: 'export',

  /** `route/index.html`, which static hosts resolve without rewrite rules. */
  trailingSlash: true,

  /**
   * Required by `output: 'export'` — the Image Optimization API is a server
   * feature. Variants are pre-generated by `scripts/build-media.mjs` and
   * declared as real `srcset`s instead (see components/atmosphere/Atmosphere).
   */
  images: {
    unoptimized: true,
  },

  reactStrictMode: true,

  /**
   * Dev-only parity. /phoenix and /frequency are directories containing
   * index.html; static hosts resolve that automatically but `next dev` does not
   * for files under `public/`, so the links 404 in development only.
   *
   * `output: 'export'` ignores rewrites, which is correct — they exist purely
   * to make development behave the way production already does.
   */
  async rewrites() {
    return [
      { source: '/phoenix', destination: '/phoenix/index.html' },
      { source: '/phoenix/', destination: '/phoenix/index.html' },
      { source: '/frequency', destination: '/frequency/index.html' },
      { source: '/frequency/', destination: '/frequency/index.html' },
    ];
  },

  compiler: {
    removeConsole: process.env.NODE_ENV === 'production' ? { exclude: ['error', 'warn'] } : false,
  },
};

export default nextConfig;
